### ISSUE TITLE
Build system

### ISSUE THREAD

**Issue by deme-rs** [rummur/rummur.github.io#6]
With the pictures, js and eventually stylesheet(s) inline, it's a bit difficult to see what is going on.
As discussed we should have a build system to collect and combine them all.

I wonder if we should avoid minification just to keep the code readable.

**Comment by ajraymond** [comment]
Now that I've thought about it some more, I think think we should avoid unnecessary abstractions. Having everything in a single file and using this file as the final product makes things clearer and easier to analyse.
