### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by deme-rs** [rummur/rummur.github.io#9]
Is there a way we can now how many times the page is visited? 
I'm not too keen on a google analytics tag, as it makes the page less standalone. Actually anything frontend falls into the same category.
Maybe gh pages can say how many times the static page was served?

**Comment by ajraymond** [comment]
Yes, have a look at https://github.com/rummur/rummur.github.io/graphs/traffic

**Comment by deme-rs** [comment]
Amazing.
